### ISSUE TITLE
HI, could you add new tanks to tank list?

### ISSUE THREAD

**Issue by 840496** [pipovec/WN8-calculator#6]
Hi.
I didn't found new tanks in https://wn8-calculator.fpcstat.cz/

Obj 252U VK7201 etc.

could add them to your tank list？
thanks.

**Comment by pipovec** [comment]
Fixed
OBJ252U
![image](https://github.com/pipovec/WN8-calculator/assets/7893722/c1ac20fc-bd04-45c8-88eb-137c5484106b)
VK7201K
![image](https://github.com/pipovec/WN8-calculator/assets/7893722/e1c6d054-ff95-4cf4-9616-cd109ff1cd06)
